# Generated by Django 3.2.4 on 2022-03-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename__id_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='_id',
            new_name='id',
        ),
    ]
